version: "3.9"

services:
  redis_notify:
      build:
          context: .
          dockerfile: Dockerfile.redis
      restart: always
      container_name: notifyredis
      hostname: redishost
      ports:
          - "6379:6379"
      volumes:
          - redis_notify_data:/data

volumes:
    redis_notify_data:

